notifications:
  email: false

dist: bionic
language: cpp

branches:
  only:
  - master

addons:
  apt:
    packages:
      - texinfo
      - ninja-build
      - python3
      - libboost-dev

install:
  - mkdir riscv-binutils
  - PATH=$PATH:$TRAVIS_BUILD_DIR/riscv-binutils/bin
  - wget http://ftp.gnu.org/gnu/binutils/binutils-2.34.tar.bz2
  - tar xjf binutils-2.34.tar.bz2
  - cd binutils-2.34
  - ./configure --target=riscv64-unknown-elf --prefix=$TRAVIS_BUILD_DIR/riscv-binutils --disable-gprof > /dev/null
  - sed -i 's/-O2/-O0/g' Makefile # Optimize compilation speed
  - make all install MAKEINFO=true > /dev/null
  - cd $TRAVIS_BUILD_DIR
  - git clone https://github.com/mipt-ilab/mipt-mips --depth=1 --recursive
  - mkdir sim && cd sim
  - cmake $TRAVIS_BUILD_DIR/mipt-mips/simulator -DCMAKE_BUILD_TYPE=Debug -G Ninja && ninja mipt-v
  - cd $TRAVIS_BUILD_DIR
  - chmod +x ./.run-tests.sh
  
script:
  - make all
  - ./.run-tests.sh $TRAVIS_BUILD_DIR/sim/mipt-v
